### ISSUE TITLE
QUnit.js Packed/Min

### ISSUE THREAD

**Issue by xenda** [frodsan/qunit-rails#1]
Tal vez qunit.js podría estar ya pack'ed o minimizado? El Asset Pipeline lo debería hacer solo también, peor por ahi que reducimos el tamaño de la gema.

**Comment by frodsan** [comment]
Sólo es para los ambientes de desarrollo y test. Creo que con un bundle install --without no habría problemas. Lo que no me gusta de minificarlo es que ver el código se pone díficil. Aún así quiero saber más al respecto. Gracias! :)

**Comment by xenda** [comment]
Aunque sería interesante ver si se puede integrar con cosas como TravisCI. No he probado QUnit como para opinar mucho, pero afecta ver su código?

**Comment by frodsan** [comment]
Para TravisCI lo hago con un rake task y phantomjs (Travis soporta phantomjs), le pasas la opción script al archivo `travis.yml` así:

```
rvm:
  - 1.9.2
script: "rake test"
```

**Comment by xenda** [comment]
TravisCI no soporta rbenv? Pero eso está genial. Jugaré el fin de semana.

**Comment by frodsan** [comment]
No creo que soporte rbenv, cuando lo configuré encontré una gema pero lo que hacía era comportarse como travis en local. No es tan grave, al menos no he tenido problemas. Tengo este template de QUnit y Phantomjs https://github.com/frodsan/test.phantomjs. Este fin cierro mis issues, así que le añadaré soporte a coffee y algunas cosas más :)

**Comment by xenda** [comment]
¿Qué parte vas a portar a Coffee? Todo QUnit.js o algo propio? Por ahi que colaboro con eso.

**Comment by frodsan** [comment]
No, QUnit no. Simplemente para hacer los tests en coffeescript. La verdad ya no usó coffee pero es como que necesario soportarlo sino no te paran bola. Claro, sería genial :).

**Comment by frodsan** [comment]
pd: Soporte para el template (me imagino con algo de nodejs?), para la gema ya lo estoy haciendo.

**Comment by xenda** [comment]
Y por qué ya no usas Coffee? :O Coffee es amor.

**Comment by frodsan** [comment]
Nunca me terminó por convencer, además de que no soy tan fan de la indentación. Digamos que para mí, sólo fue una ilusión jajaja :)

**Comment by xenda** [comment]
A mi me gusta la indentación en cosas declarativas como HAML y JS. Prefiero cierres explícitos en código como Ruby. 

Lo que me gusta de Coffee es que elimina mucho de las cosas extras de JS que nunca me convencieron (semicolons :D), y en general lo deja más limpio. De hecho es casi lo mismo, pero ligeramente mejor (subjetivamente, claro). Lo que extraño aún es una consola integrada con Web Inspector.

**Comment by frodsan** [comment]
jaja sí eso último también. Personalmente no tengo problemas con los `;` o `{}`, talvez más con cosas como `==` que deberían eliminarse. También ya dejé HAML, no conjugaba muy bien con handlebars jaja. Es cuestión de gustos.

**Comment by xenda** [comment]
Al menos el == lo vuelve === solo :P. Creo que lo que me gusta de HAML/CoffeeScript y similares es que, al cambiar el contexto visual de lo que hago, me permite enfocarme en cosas que con HTML puro, como base, no hago. Por ejemplo, en HTML no me molesta agregar atributos o divs. En HAML si y me preocupa más la organización y la estructura.

Cuando usaba HTML ordenaba e indentaba mucho mi código, pero no era muy claro el contenido de la estructura. Encuentro que HAML me lo muestra más claro (de nuevo, YMMV).

Coffee llega por el mismo camino. Me hace querer tener mejor código. Definitivamente es un tema de disciplina, y es subjetivo. Las mismas razones por las que prefiero Ruby a Python.

Y acá una araña
![Una araña](http://img.gawkerassets.com/img/17nqusc8i2wbbjpg/original.jpg)

**Comment by frodsan** [comment]
jaja así sí se ven adorables :3
