### ISSUE TITLE
Foundation javascripts cause it to throw lots of errors

### ISSUE THREAD

**Issue by jakecraige** [frodsan/qunit-rails#15]
When i have by `#= require foundation` in my application.js.coffee file it attempts fails loading the first file with this error `Uncaught TypeError: Layer must be a document node` and then the rest throw errors because foundation wasn't defined

**Comment by elsurudo** [comment]
I am having the same issue. Have you found a workaround, by any chance?

**Comment by jakecraige** [comment]
Sadly no.. I just has to not include foundation in my tests

On Thursday, January 9, 2014, Ernest Surudo wrote:

> I am having the same issue. Have you found a workaround, by any chance?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/frodsan/qunit-rails/issues/15#issuecomment-31920135
> .

## 

See my vizify bio!
[image: James Craige's Visual
Thumbprint]https://www.vizify.com/es/501a695db146e100020002bd

**Comment by elsurudo** [comment]
Darn. I'm trying to do some integration testing with Ember.js and QUnit, so I need to include Foundation to have my whole app working...

**Comment by frodsan** [comment]
Could you provide a test app to reproduce this?

**Comment by jakecraige** [comment]
here's one https://github.com/jakecraige/foundation-qunit-failure-example 

It's just a base app with foundation and qunit-rails setup and throws the errors referenced above

**Comment by elsurudo** [comment]
Nice, beat me to the punch :)

**Comment by frodsan** [comment]
I released 0.0.6, could you test it please? :smile:

**Comment by jakecraige** [comment]
That fixed it. Nice job! I wonder what it was. Looks like foundation was updated as well recently.

Either way, with the newest of both no more errors

**Comment by frodsan** [comment]
TBH, I think it was a problem in foundation. I didn't do anything :p. Anyway, I'm glad that it's fixed now :).

**Comment by elsurudo** [comment]
Beautiful, just upgraded foundation-rails, and works for me too :)
