### ISSUE TITLE
Google maps and fixtures

### ISSUE THREAD

**Issue by ilandimnik** [frodsan/qunit-rails#2]
Hi, 

I have two issues - 

(1) I want to be able to run tests with google maps. For that I need to able to add more script sources to index.html.erb (in my case google maps). How do I do that?

(2) How do I add Qunit fixture to the same index file?

Cheers.

**Comment by frodsan** [comment]
@ilandimnik I apologize to be so late to answer you. I was working with the current version and i'm not 100% satisfied. I will be working in a new version and i will consider your issues. thx again.
