### ISSUE TITLE
Add documentation about overriding index.html

### ISSUE THREAD

**Issue by frodsan** [frodsan/qunit-rails#4]

**Comment by sly7-7** [comment]
Can you briefly explain me how to do it ?

**Comment by frodsan** [comment]
@sly7-7 Check https://github.com/frodsan/qunit-rails#%C2%A0overriding-indexhtml. I would like to change this, but right now I'm kind of busy :/. Thanks :)

**Comment by sly7-7** [comment]
Thanks :). In fact I was encountering a problem with my app which is based on ember.js. All was ok until I wanted to define a custom rootElement for the application. 
Then when the qunit tests where running, Ember thrown an error saying it can't find the rootElement... I worked around that by adding this at runtime with jQuery. But I think having a correct custom index.html.erb defining this rootElement should be better. Anyway, thanks a lot taking the time to answer.
